---
bind:
  forwards:
    - '1.1.1.1'
  listen_address:
    - 'any'
  allow_query:
    - '127.0.0.1'
    - '::1'
    - '10.0.0.0/8'
  # OPTIONAL:
  # allow_transfer:
  #   - '10.172.42.1'
  # allow_notify:
  #   - '10.172.42.1'
  # also_notify:
  #   - '10.172.42.1'
zones:
  test.local:
    serial: ["2024062201"]
    records:
      a:
        dns: ["10.192.1.1"]
        ansible: ["10.192.1.2"]
      aaaa:
        dns: ["fd4b:7618:f5ec:798d::1"]
        ansible: ["fd4b:7618:f5ec:798d::2"]
      cname:
        test-cname: ["dns"]
  1.192.10.in-addr.arpa:
    serial: ["2024062201"]
    records:
      1: ["dns"]
      2: ["ansible"]
  d.8.9.7.c.e.5.f.8.1.6.7.b.4.d.f.ip6.arpa:
    serial: ["2024062201"]
    records:
      1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0: ["dns"]
      2.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0: ["ansible"]
