---
- name: Install bind9
  ansible.builtin.apt:
    pkg:
      - bind9
    update_cache: true
- name: Copy named.conf.local
  ansible.builtin.template:
    src: templates/etc/bind/named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: bind
    mode: '0644'
- name: Copy named.conf.options
  ansible.builtin.template:
    src: templates/etc/bind/named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: '0644'
- name: Create zones directory
  ansible.builtin.file:
    state: directory
    path: /etc/bind/zones
    owner: root
    group: bind
    mode: '0750'
- name: Create bind logs directory
  ansible.builtin.file:
    state: directory
    path: /var/log/named
    owner: bind
    group: bind
    mode: '0750'
- name: Modify forward zone
  ansible.builtin.template:
    src: templates/etc/bind/zones/{{ item }}.j2
    dest: /etc/bind/zones/{{ item }}
    owner: root
    group: bind
    mode: '0640'
  loop: "{{ zones.keys() }}"
  notify: restart bind
