---
zones:
  domus.local:
    serial: ["2022090201"]
    records:
      a:
        dns: ["10.192.1.1"]
        ansible: ["10.192.1.2"]
      cname:
        test-cname: ["dns"]
  1.42.10.in-addr.arpa:
    serial: ["2022090201"]
    records:
      a:
        dns: ["1"]
        ansible: ["2"]
